
#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "6"
#define VORPALINE_VERSION_PATCH "3"
#define VORPALINE_VERSION "1.6.3"
#define VORPALINE_BUILD_NUMBER "1"
#define VORPALINE_BUILD_DATE "1"
#define VORPALINE_SVN_REVISION "1"

#endif

