
#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "3"
#define VORPALINE_VERSION_PATCH "4"
#define VORPALINE_VERSION "1.3.4"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE "2016-06-21 18:10:42"
#define VORPALINE_SVN_REVISION "2191"

#endif

